fos_user_security:
    resource: routing/security.yml

fos_user_profile:
    resource: routing/profile.yml
    prefix: /profile

fos_user_register:
    resource: routing/registration.yml
    prefix: /register

fos_user_resetting:
    resource: routing/resetting.yml
    prefix: /resetting

fos_user_change_password:
    resource: routing/change_password.yml
    prefix: /profile

user_Add_user:
    path:     /adduser
    defaults: { _controller: BackendBackendBundle:Manager:register }